### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Alicture** [emptyhua/raspberry_pi_helper#1]
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/pi/raspberry_pi_helper/node_modules/bluetooth-hci-socket/build/Release/binding.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/raspberry_pi_helper/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Alicture** [comment]
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v51-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@7.6.0 (node-v51 ABI) (falling back to source compile with node-gyp)

**Comment by Alicture** [comment]
问题解决了，我是使用nvm安装nodejs的，导致了sudo 下使用node的问题
以下一条命令可以解决：
n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
